apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
